Implement logger and add colum 'is nullable'
Thaneshwor/python-data-profiler pull request #6
Opened 2019-09-06 07:25 UTC by Thaneshwor

1. Change column header 'Actual Datytype' to 'Maximum Datatype' while displaying  columns and their maximum datatype available.
2.Add column 'is nullable' while displaying  columns and available datatypes and remove 'None' from column 'datatypes' .
3.Add code for generating error.log file 
4.Code change for finding datatype
5.Logic change for finding erroneous column
5.Code refactor

2019-09-06 08:13 UTC, romitamgai requested changes

2019-09-06 08:13 UTC, romitamgai commented on data_profiller/utils/data_collection.py
> +
no need for extra line

2019-09-06 08:13 UTC, romitamgai commented on data_profiller/utils/data_collection.py
> +        return True
add an extra line before return

2019-09-06 08:13 UTC, romitamgai commented on data_profiller/utils/data_collection.py
> +        x = float(val)
no need for variable assignment here

2019-09-06 08:13 UTC, romitamgai commented on data_profiller/utils/data_collection.py
> +
no need for extra line

2019-09-06 08:13 UTC, romitamgai commented on data_profiller/utils/file_operation.py
> +        print('error occuure---------------------', e)
typo

2019-09-07 08:55 UTC, SafalPandey requested changes
Use early returns.

2019-09-07 08:55 UTC, SafalPandey commented on data_profiller/utils/data_collection.py
> +        dtype_cell = 'date'
Why are you assigning these values if all you do is return them later? You can return right away.
```suggestion
        return 'date'
```

2019-09-07 08:55 UTC, SafalPandey commented on data_profiller/utils/data_collection.py
> +        dtype_cell = 'integer'
```suggestion
        return 'integer'
```

2019-09-07 08:55 UTC, SafalPandey commented on data_profiller/utils/data_collection.py
> +        dtype_cell = 'float'
```suggestion
        return 'float'
```

2019-09-07 08:55 UTC, SafalPandey commented on data_profiller/utils/data_collection.py
>          dtype_cell = None
```suggestion
        return None
```

2019-09-07 08:55 UTC, SafalPandey commented on data_profiller/utils/data_collection.py
>      else:
```suggestion

```

2019-09-07 08:55 UTC, SafalPandey commented on data_profiller/utils/data_collection.py
>      return dtype_cell
```suggestion

```

2019-09-07 09:01 UTC, SafalPandey commented on data_profiller/utils/data_collection.py
> +        dtype_cell = 'string'
```suggestion
    return 'string'
```

2019-09-07 09:06 UTC, SafalPandey commented on data_profiller/utils/data_collection.py
> +def isInt(val):
Use snake case.
```suggestion
def is_int(val):
```

2019-09-07 09:06 UTC, SafalPandey commented on data_profiller/utils/data_collection.py
> +def isFloat(val):
```suggestion
def is_float(val):
```

2019-09-07 09:12 UTC, SafalPandey commented on data_profiller/utils/data_collection.py
> +        return isinstance(int(float(val)), int)
What's the point of `float(val)` here? Add a comment.

2019-09-16 11:13 UTC, romitamgai approved these changes

2019-09-16 11:14 UTC, merged